# Generated by Django 4.1.3 on 2022-11-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0012_alter_friendship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('default', 'default'), ('send', 'send'), ('accepted', 'accepted')], default='default', max_length=12),
        ),
    ]
