# Generated by Django 4.1.3 on 2022-11-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default=1321, max_length=4),
        ),
    ]
