# Generated by Django 4.1.3 on 2022-11-11 22:26

import custom_user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default=custom_user.utils.generate_otp, max_length=4),
        ),
    ]
