# Generated by Django 4.1.3 on 2022-11-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0012_alter_friendship_status'),
        ('social_interaction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='social_app.profile'),
        ),
    ]
