# Generated by Django 4.1.3 on 2022-11-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0013_alter_friendship_status'),
        ('social_interaction_app', '0005_alter_like_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_link', to='social_app.profile'),
        ),
    ]
