# Generated by Django 4.1.3 on 2022-11-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_interaction_app', '0006_alter_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'True'), ('Unlike', 'False')], max_length=8),
        ),
    ]
