# Generated by Django 4.1.3 on 2022-11-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_interaction_app', '0007_alter_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=8),
        ),
    ]
