# Generated by Django 4.1.3 on 2022-11-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_interaction_app', '0009_remove_like_value_like_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='pliked',
        ),
    ]
